### ISSUE TITLE
音乐人信息部分报错

### ISSUE THREAD

**Issue by 777-cun** [chen310/NeteaseCloudMusicTasks#11]
Traceback (most recent call last):
  File "index.py", line 278, in <module>
    start({}, {})
  File "index.py", line 83, in start
    user.musician_task()
  File "/ql/scripts/chen310_NeteaseCloudMusicTasks/user.py", line 777, in musician_task
    if data['playCount'] is None:
TypeError: 'NoneType' object is not subscriptable

**Comment by chen310** [comment]
> Traceback (most recent call last): File "index.py", line 278, in start({}, {}) File "index.py", line 83, in start user.musician_task() File "/ql/scripts/chen310_NeteaseCloudMusicTasks/user.py", line 777, in musician_task if data['playCount'] is None: TypeError: 'NoneType' object is not subscriptable

你更新试试
