### ISSUE TITLE
大佬，可以帮我看一下是哪里填写出错了吗

### ISSUE THREAD

**Issue by 747337777a** [chen310/NeteaseCloudMusicTasks#17]
日志:
Traceback (most recent call last):
  File "index.py", line 281, in <module>
    start()
  File "index.py", line 41, in start
    config = json5.load(f)
  File "/usr/lib/python3.8/site-packages/json5/lib.py", line 46, in load
    return loads(s, encoding=encoding, cls=cls, object_hook=object_hook,
  File "/usr/lib/python3.8/site-packages/json5/lib.py", line 82, in loads
    raise ValueError(err)
ValueError: <string>:2 Unexpected """ at column 5

**Comment by chen310** [comment]
Dumplicate of #14
