### ISSUE TITLE
运行失败START RequestId: 54f0955b-e7d0-4060-aa8a-2e15f5c8dc17  Init Report RequestId: 54f0955b-e7d0-4060-aa8a-2e15f5c8dc17 Coldstart: 1108ms (PullCode: 176ms InitRuntime: 6ms InitFunction: 926ms) Memory: 128MB MemUsage: 24.07MB  ERROR RequestId: 54f0955b-e7d0-4060-aa8a-2e15f5c8dc17 Result: Traceback (most recent call last):   File "/var/user/index.py", line 154, in main_handler     start(event, context)   File "/var/user/index.py", line 52, in start     with open('config.json', 'r', encoding='utf-8') as f: FileNotFoundError: [Errno 2] No such file or directory: 'config.json'  END RequestId: 54f0955b-e7d0-4060-aa8a-2e15f5c8dc17  Report RequestId: 54f0955b-e7d0-4060-aa8a-2e15f5c8dc17 Duration: 2ms Memory: 128MB MemUsage: 39.18MB

### ISSUE THREAD

**Issue by wzzyw** [chen310/NeteaseCloudMusicTasks#193]
![1650727265662](https://user-images.githubusercontent.com/89442802/164912378-45771f7a-ad9f-4b70-882b-613f016d2695.png)
START RequestId: 54f0955b-e7d0-4060-aa8a-2e15f5c8dc17

Init Report RequestId: 54f0955b-e7d0-4060-aa8a-2e15f5c8dc17 Coldstart: 1108ms (PullCode: 176ms InitRuntime: 6ms InitFunction: 926ms) Memory: 128MB MemUsage: 24.07MB

ERROR RequestId: 54f0955b-e7d0-4060-aa8a-2e15f5c8dc17 Result: Traceback (most recent call last):   File "/var/user/index.py", line 154, in main_handler     start(event, context)   File "/var/user/index.py", line 52, in start     with open('config.json', 'r', encoding='utf-8') as f: FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

END RequestId: 54f0955b-e7d0-4060-aa8a-2e15f5c8dc17

Report RequestId: 54f0955b-e7d0-4060-aa8a-2e15f5c8dc17 Duration: 2ms Memory: 128MB MemUsage: 39.18MB

**Comment by BlueHtml** [comment]
@wzzyw 没有`config.json`这个文件。你需要把`config.example.json`复制为`config.json`，并且配置好各种数据
