### ISSUE TITLE
运行到VIP成长值时报错

### ISSUE THREAD

**Issue by Javonne-do** [chen310/NeteaseCloudMusicTasks#3]
错误如下：
`Traceback (most recent call last):
  File "/ql/scripts/NeteaseCloudMusicTasks/index.py", line 275, in <module>
    start({}, {})
  File "/ql/scripts/NeteaseCloudMusicTasks/index.py", line 84, in start
    user.vip_task()
  File "/ql/scripts/NeteaseCloudMusicTasks/user.py", line 793, in vip_task
    tasks = self.user_setting["vip_task"]
KeyError: 'vip_task'
`

**Comment by Javonne-do** [comment]
已解决，发现是10版本得config.json更新了东西，已成功在青龙面板部署成功
