### ISSUE TITLE
在服务器端报错缺少requests模块,已经执行pip命令安装

### ISSUE THREAD

**Issue by lq-259** [chen310/NeteaseCloudMusicTasks#34]
看到别人也有缺模块的问题，用你回复的方法尝试也并未解决
NeteaseCloudMusicTasks   main ±  python index.py                        Traceback (most recent call last):
  File "index.py", line 4, in <module>
    import requests
ImportError: No module named requests
 ✘ ⚡ root@localhost  ~/NeteaseCloudMusicTasks   main ±  pip install -r requirements.txt      Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: requests==2.26.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 1)) (2.26.0)
Requirement already satisfied: json5==0.9.6 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 2)) (0.9.6)
Requirement already satisfied: pycryptodomex==3.12.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 3)) (3.12.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests==2.26.0->-r requirements.txt (line 1)) (1.26.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests==2.26.0->-r requirements.txt (line 1)) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests==2.26.0->-r requirements.txt (line 1)) (2.0.10)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests==2.26.0->-r requirements.txt (line 1)) (3.3)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 ⚡ root@localhost  ~/NeteaseCloudMusicTasks   main ±  python3 -m pip install -r requirements.txt
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: requests==2.26.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 1)) (2.26.0)
Requirement already satisfied: json5==0.9.6 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 2)) (0.9.6)
Requirement already satisfied: pycryptodomex==3.12.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 3)) (3.12.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests==2.26.0->-r requirements.txt (line 1)) (2.0.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests==2.26.0->-r requirements.txt (line 1)) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests==2.26.0->-r requirements.txt (line 1)) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests==2.26.0->-r requirements.txt (line 1)) (1.26.8)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 ⚡ root@localhost  ~/NeteaseCloudMusicTasks   main ±  python index.py                        Traceback (most recent call last):
  File "index.py", line 4, in <module>
    import requests
ImportError: No module named requests
 ✘ ⚡ root@localhost  ~/NeteaseCloudMusicTasks   main ± 

**Comment by lq-259** [comment]
> `python3 index.py`

哦好了，感谢
